### ISSUE TITLE
Create new table variation

### ISSUE THREAD

**Issue by jedgar1mx** [CityOfDetroit/COD-Design-System#104]
## Issue
We need to re-create the responsive table variation used on the buses page.

## Desktop

![Image](https://github.com/CityOfDetroit/COD-Design-System/assets/21081923/0053b0ee-86c2-481d-b95b-fb33046aebcb)

## Mobile

![Image](https://github.com/CityOfDetroit/COD-Design-System/assets/21081923/2962b953-e28f-4b72-af69-7b047eece0c9)

**Comment by maxatdetroit** [comment]
@jedgar1mx , @bankovic how would you both feel about responsive options like these (instead of the exact same responsive layout currently used)? Of course, we would use our theme colors (instead of grey).

**Stacked borderless table with headers**
<img width="312" alt="Screenshot 2023-10-20 at 9 51 56 AM" src="https://github.com/CityOfDetroit/COD-Design-System/assets/143553259/71f83431-7824-4d96-b82e-dcf8eb3f7af0">

**Stacked borderless table**
<img width="266" alt="Screenshot 2023-10-20 at 9 55 29 AM" src="https://github.com/CityOfDetroit/COD-Design-System/assets/143553259/a52e7515-d3ec-4b4a-b27e-596002a51687">

Here's some more details & examples: https://designsystem.digital.gov/components/table/#responsive-stacked-table-2

I'm in favor of these designs for the following reasons:
* The current design takes up a lot of screen real estate repeating the headers multiple times, whereas the designs here include the header in the cell and reduce screen usage.
* With the headers repeated in the current design, the attention is immediately and repeatedly drawn to the header on each row which is not desirable. The header should just be a visual cue to understand the info, not the main focal point. 
* The 'stacked with headers' option is nice for tables like the bus schedule where the table headers and the table cells are very similar (almost duplicates). It would be natural to set the header to the route name (instead of showing 'route name').

Please let me know what you both think and if I'm missing come considerations there.

**Comment by bankovic** [comment]
I would feel pretty good, as long as editors can edit the tables. :)

**Comment by maxatdetroit** [comment]
Closing this out since #112 is merged.
